// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Button documents
 */
interface ButtonDocumentData {
  /**
   * Variant field in *Button*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: button.variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<"primary" | "secondary", "filled">;

  /**
   * Size field in *Button*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: xs
   * - **API ID Path**: button.size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  size: prismic.SelectField<"xs" | "sm" | "base" | "lg" | "xl", "filled">;

  /**
   * Full Width field in *Button*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: button.full_width
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  full_width: prismic.BooleanField;
}

/**
 * Button document from Prismic
 *
 * - **API ID**: `button`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ButtonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ButtonDocumentData>, "button", Lang>;

/**
 * Item in *Footer → Slogan Keys*
 */
export interface FooterDocumentDataSloganKeysItem {
  /**
   * word field in *Footer → Slogan Keys*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Use "key" words, which is part of the slogan on same row.
   * - **API ID Path**: footer.slogan_keys[].word
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  word: prismic.RichTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slogan field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Add your current slogan into footer. WIll be shown on right side, with same row as the "key" words.
   * - **API ID Path**: footer.slogan
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slogan: prismic.RichTextField;

  /**
   * Slogan Keys field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slogan_keys[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slogan_keys: prismic.GroupField<Simplify<FooterDocumentDataSloganKeysItem>>;

  /**
   * Social Icons field in *Footer*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_icons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_icons: prismic.ContentRelationshipField<"icons_list">;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for heroicon documents
 */
interface HeroiconDocumentData {
  /**
   * variant field in *heroicon*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose variant for the current icon. By default "solid" variant will be used for the icon.
   * - **Default Value**: solid
   * - **API ID Path**: heroicon.variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<"solid" | "outline" | "mini", "filled">;

  /**
   * name field in *heroicon*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: arrow-small-down
   * - **API ID Path**: heroicon.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<
    | "arrow-small-down"
    | "arrow-small-up"
    | "arrow-small-right"
    | "arrow-up-right",
    "filled"
  >;
}

/**
 * heroicon document from Prismic
 *
 * - **API ID**: `heroicon`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeroiconDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HeroiconDocumentData>,
    "heroicon",
    Lang
  >;

/**
 * Item in *Icons List → Collection*
 */
export interface IconsListDocumentDataCollectionItem {
  /**
   * name field in *Icons List → Collection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icons_list.collection[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * icon field in *Icons List → Collection*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: tailwindcss
   * - **API ID Path**: icons_list.collection[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    | "tailwindcss"
    | "graphql"
    | "react"
    | "nextjs"
    | "GitHub"
    | "LinkedIn"
    | "Twitter",
    "filled"
  >;

  /**
   * href field in *Icons List → Collection*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional value for current icon. Can be used for example with social icons, where you want to redirect user into LinkedIn etc.
   * - **API ID Path**: icons_list.collection[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField;
}

/**
 * Content for Icons List documents
 */
interface IconsListDocumentData {
  /**
   * Show Icons field in *Icons List*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: icons_list.show_icons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_icons: prismic.BooleanField;

  /**
   * Collection field in *Icons List*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icons_list.collection[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  collection: prismic.GroupField<Simplify<IconsListDocumentDataCollectionItem>>;
}

/**
 * Icons List document from Prismic
 *
 * - **API ID**: `icons_list`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IconsListDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IconsListDocumentData>,
    "icons_list",
    Lang
  >;

/**
 * Item in *Image Gallery → Gallery*
 */
export interface ImageGalleryDocumentDataGalleryItem {
  /**
   * image field in *Image Gallery → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Image Gallery documents
 */
interface ImageGalleryDocumentData {
  /**
   * Gallery field in *Image Gallery*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<ImageGalleryDocumentDataGalleryItem>>;
}

/**
 * Image Gallery document from Prismic
 *
 * - **API ID**: `image_gallery`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImageGalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ImageGalleryDocumentData>,
    "image_gallery",
    Lang
  >;

/**
 * Content for Image Mask documents
 */
interface ImageMaskDocumentData {
  /**
   * variant field in *Image Mask*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose mask variant (default is "avatar")
   * - **Default Value**: avatar
   * - **API ID Path**: image_mask.variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<"avatar" | "fullWidth", "filled">;
}

/**
 * Image Mask document from Prismic
 *
 * - **API ID**: `image_mask`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImageMaskDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ImageMaskDocumentData>,
    "image_mask",
    Lang
  >;

type LandingPageDocumentDataSlicesSlice =
  | ContentBlockSliceSlice
  | HeroSliceSlice
  | CardSliceSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Item in *navigation → Navigation Links*
 */
export interface NavigationDocumentDataNavigationLinksItem {
  /**
   * Link Name field in *navigation → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_links[].link_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_name: prismic.KeyTextField;

  /**
   * Link Href field in *navigation → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_links[].link_href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_href: prismic.LinkField;
}

/**
 * Content for navigation documents
 */
interface NavigationDocumentData {
  /**
   * position field in *navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: navigation.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  position: prismic.BooleanField;

  /**
   * Navigation Title field in *navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  navigation_title: prismic.KeyTextField;

  /**
   * Navigation Links field in *navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_links: prismic.GroupField<
    Simplify<NavigationDocumentDataNavigationLinksItem>
  >;
}

/**
 * navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type ProjectDocumentDataSlicesSlice =
  | ContentBlockSliceSlice
  | HeroSliceSlice
  | StatsBlockSliceSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes =
  | ButtonDocument
  | FooterDocument
  | HeroiconDocument
  | IconsListDocument
  | ImageGalleryDocument
  | ImageMaskDocument
  | LandingPageDocument
  | NavigationDocument
  | ProjectDocument;

/**
 * Primary content in *CardSlice → Primary*
 */
export interface CardSliceSliceDefaultPrimary {
  /**
   * title field in *CardSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * subtitle field in *CardSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Primary content in *CardSlice → Items*
 */
export interface CardSliceSliceDefaultItem {
  /**
   * Card Image field in *CardSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Name field in *CardSlice → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter name for current card item.
   * - **API ID Path**: card_slice.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Collection field in *CardSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].collection
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  collection: prismic.ContentRelationshipField<"icons_list">;

  /**
   * Description field in *CardSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description for current card item.
   * - **API ID Path**: card_slice.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Icon field in *CardSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  icon: prismic.ContentRelationshipField<"heroicon">;

  /**
   * Button field in *CardSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.ContentRelationshipField<"button">;

  /**
   * Button Label field in *CardSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Button Href field in *CardSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.ContentRelationshipField<"project">;
}

/**
 * Default variation for CardSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardSliceSliceDefaultPrimary>,
  Simplify<CardSliceSliceDefaultItem>
>;

/**
 * Slice variation for *CardSlice*
 */
type CardSliceSliceVariation = CardSliceSliceDefault;

/**
 * CardSlice Shared Slice
 *
 * - **API ID**: `card_slice`
 * - **Description**: CardSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceSlice = prismic.SharedSlice<
  "card_slice",
  CardSliceSliceVariation
>;

/**
 * Primary content in *ContentBlockSlice → Primary*
 */
export interface ContentBlockSliceSliceDefaultPrimary {
  /**
   * title field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * subtitle field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Hashtag field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.hashtag
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hashtag: prismic.ContentRelationshipField<"icons_list">;

  /**
   * Stack field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.stack
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  stack: prismic.ContentRelationshipField<"icons_list">;

  /**
   * Content field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Images field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.images
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  images: prismic.ContentRelationshipField<"image_gallery">;
}

/**
 * Default variation for ContentBlockSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentBlockSliceSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ContentBlockSlice → Primary*
 */
export interface ContentBlockSliceSliceTextOnlyPrimary {
  /**
   * Content field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Text Only variation for ContentBlockSlice Slice
 *
 * - **API ID**: `textOnly`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSliceSliceTextOnly = prismic.SharedSliceVariation<
  "textOnly",
  Simplify<ContentBlockSliceSliceTextOnlyPrimary>,
  never
>;

/**
 * Slice variation for *ContentBlockSlice*
 */
type ContentBlockSliceSliceVariation =
  | ContentBlockSliceSliceDefault
  | ContentBlockSliceSliceTextOnly;

/**
 * ContentBlockSlice Shared Slice
 *
 * - **API ID**: `content_block_slice`
 * - **Description**: ContentBlockSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSliceSlice = prismic.SharedSlice<
  "content_block_slice",
  ContentBlockSliceSliceVariation
>;

/**
 * Primary content in *HeroSlice → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Title field in *HeroSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for Hero, uses <h1 /> tag.
   * - **API ID Path**: hero_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Subtitle is under the Hero title.
   * - **API ID Path**: hero_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Hero Image field in *HeroSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Image Mask field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.image_mask
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_mask: prismic.ContentRelationshipField<"image_mask">;

  /**
   * icon field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  icon: prismic.ContentRelationshipField<"heroicon">;

  /**
   * Button field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.ContentRelationshipField<"button">;

  /**
   * Button Label field in *HeroSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter label value for your button. Is visible for both button and links.
   * - **API ID Path**: hero_slice.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Button Href field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.ContentRelationshipField<"landing_page">;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSlice → Primary*
 */
export interface HeroSliceSliceFullWidthPrimary {
  /**
   * Title field in *HeroSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for Hero, uses <h1 /> tag.
   * - **API ID Path**: hero_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Subtitle is under the Hero title.
   * - **API ID Path**: hero_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Hero Image field in *HeroSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Image Mask field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.image_mask
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_mask: prismic.ContentRelationshipField<"image_mask">;
}

/**
 * Full Width variation for HeroSlice Slice
 *
 * - **API ID**: `fullWidth`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceFullWidth = prismic.SharedSliceVariation<
  "fullWidth",
  Simplify<HeroSliceSliceFullWidthPrimary>,
  never
>;

/**
 * Primary content in *HeroSlice → Primary*
 */
export interface HeroSliceSliceGoBackPrimary {
  /**
   * Title field in *HeroSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for Hero, uses <h1 /> tag.
   * - **API ID Path**: hero_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Hero Image field in *HeroSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Image Mask field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.image_mask
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_mask: prismic.ContentRelationshipField<"image_mask">;
}

/**
 * Go Back variation for HeroSlice Slice
 *
 * - **API ID**: `goBack`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceGoBack = prismic.SharedSliceVariation<
  "goBack",
  Simplify<HeroSliceSliceGoBackPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation =
  | HeroSliceSliceDefault
  | HeroSliceSliceFullWidth
  | HeroSliceSliceGoBack;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

/**
 * Primary content in *StatsBlockSlice → Items*
 */
export interface StatsBlockSliceSliceDefaultItem {
  /**
   * value field in *StatsBlockSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_block_slice.items[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;

  /**
   * icon field in *StatsBlockSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_block_slice.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  icon: prismic.ContentRelationshipField<"heroicon">;

  /**
   * href field in *StatsBlockSlice → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: For href to work, both this and icon has to be filled so that user will be redirected.
   * - **API ID Path**: stats_block_slice.items[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField;

  /**
   * name field in *StatsBlockSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_block_slice.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Default variation for StatsBlockSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsBlockSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<StatsBlockSliceSliceDefaultItem>
>;

/**
 * Slice variation for *StatsBlockSlice*
 */
type StatsBlockSliceSliceVariation = StatsBlockSliceSliceDefault;

/**
 * StatsBlockSlice Shared Slice
 *
 * - **API ID**: `stats_block_slice`
 * - **Description**: StatsBlockSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsBlockSliceSlice = prismic.SharedSlice<
  "stats_block_slice",
  StatsBlockSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ButtonDocument,
      ButtonDocumentData,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSloganKeysItem,
      HeroiconDocument,
      HeroiconDocumentData,
      IconsListDocument,
      IconsListDocumentData,
      IconsListDocumentDataCollectionItem,
      ImageGalleryDocument,
      ImageGalleryDocumentData,
      ImageGalleryDocumentDataGalleryItem,
      ImageMaskDocument,
      ImageMaskDocumentData,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataNavigationLinksItem,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      AllDocumentTypes,
      CardSliceSlice,
      CardSliceSliceDefaultPrimary,
      CardSliceSliceDefaultItem,
      CardSliceSliceVariation,
      CardSliceSliceDefault,
      ContentBlockSliceSlice,
      ContentBlockSliceSliceDefaultPrimary,
      ContentBlockSliceSliceTextOnlyPrimary,
      ContentBlockSliceSliceVariation,
      ContentBlockSliceSliceDefault,
      ContentBlockSliceSliceTextOnly,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceFullWidthPrimary,
      HeroSliceSliceGoBackPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      HeroSliceSliceFullWidth,
      HeroSliceSliceGoBack,
      StatsBlockSliceSlice,
      StatsBlockSliceSliceDefaultItem,
      StatsBlockSliceSliceVariation,
      StatsBlockSliceSliceDefault,
    };
  }
}
