// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Button documents */
interface ButtonDocumentData {
  /**
   * Variant field in *Button*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: button.variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<"primary" | "secondary">;
  /**
   * Size field in *Button*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: button.size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"xs" | "sm" | "base" | "lg" | "xl">;
  /**
   * Full Width field in *Button*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: button.full_width
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  full_width: prismic.BooleanField;
}
/**
 * Button document from Prismic
 *
 * - **API ID**: `button`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ButtonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ButtonDocumentData>, "button", Lang>;
/** Content for Image Mask documents */
interface ImageMaskDocumentData {
  /**
   * variant field in *Image Mask*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose mask variant (default is "avatar")
   * - **Default Value**: avatar
   * - **API ID Path**: image_mask.variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<"avatar" | "aarni", "filled">;
}
/**
 * Image Mask document from Prismic
 *
 * - **API ID**: `image_mask`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImageMaskDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ImageMaskDocumentData>,
    "image_mask",
    Lang
  >;
/** Content for page documents */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>;
}
/**
 * Slice for *page → Slice Zone*
 *
 */
type LandingPageDocumentDataSlicesSlice = HeroSliceSlice | AarniSliceSlice;
/**
 * page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;
/** Content for navigation documents */
interface NavigationDocumentData {
  /**
   * color field in *navigation*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  color: prismic.ContentRelationshipField<
    | "theme_50"
    | "theme_100"
    | "theme_200"
    | "theme_300"
    | "theme_400"
    | "theme_500"
    | "theme_600"
    | "theme_700"
    | "theme_800"
    | "theme_900"
    | "theme_950"
  >;
  /**
   * position field in *navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: navigation.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  position: prismic.BooleanField;
  /**
   * Navigation Title field in *navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  navigation_title: prismic.KeyTextField;
  /**
   * Navigation Links field in *navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  navigation_links: prismic.GroupField<
    Simplify<NavigationDocumentDataNavigationLinksItem>
  >;
}
/**
 * Item in navigation → Navigation Links
 *
 */
export interface NavigationDocumentDataNavigationLinksItem {
  /**
   * Link Name field in *navigation → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_links[].link_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  link_name: prismic.KeyTextField;
  /**
   * Link Href field in *navigation → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_links[].link_href
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link_href: prismic.LinkField;
}
/**
 * navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;
/** Content for theme_100 documents */
interface Theme100DocumentData {
  /**
   * light field in *theme_100*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_100.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme100DocumentDataLightItem>>;
}
/**
 * Item in theme_100 → light
 *
 */
export interface Theme100DocumentDataLightItem {
  /**
   * name field in *theme_100 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_100.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-100">;
  /**
   * code field in *theme_100 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_100.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"f5f5f5">;
}
/**
 * theme_100 document from Prismic
 *
 * - **API ID**: `theme_100`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme100Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme100DocumentData>,
    "theme_100",
    Lang
  >;
/** Content for theme_200 documents */
interface Theme200DocumentData {
  /**
   * light field in *theme_200*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_200.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme200DocumentDataLightItem>>;
}
/**
 * Item in theme_200 → light
 *
 */
export interface Theme200DocumentDataLightItem {
  /**
   * name field in *theme_200 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_200.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-200">;
  /**
   * code field in *theme_200 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_200.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"e5e5e5">;
}
/**
 * theme_200 document from Prismic
 *
 * - **API ID**: `theme_200`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme200Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme200DocumentData>,
    "theme_200",
    Lang
  >;
/** Content for theme_300 documents */
interface Theme300DocumentData {
  /**
   * light field in *theme_300*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_300.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme300DocumentDataLightItem>>;
}
/**
 * Item in theme_300 → light
 *
 */
export interface Theme300DocumentDataLightItem {
  /**
   * name field in *theme_300 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_300.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-300">;
  /**
   * code field in *theme_300 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_300.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"d4d4d4">;
}
/**
 * theme_300 document from Prismic
 *
 * - **API ID**: `theme_300`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme300Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme300DocumentData>,
    "theme_300",
    Lang
  >;
/** Content for theme_400 documents */
interface Theme400DocumentData {
  /**
   * light field in *theme_400*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_400.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme400DocumentDataLightItem>>;
}
/**
 * Item in theme_400 → light
 *
 */
export interface Theme400DocumentDataLightItem {
  /**
   * name field in *theme_400 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_400.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-400">;
  /**
   * code field in *theme_400 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_400.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"a3a3a3">;
}
/**
 * theme_400 document from Prismic
 *
 * - **API ID**: `theme_400`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme400Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme400DocumentData>,
    "theme_400",
    Lang
  >;
/** Content for theme_50 documents */
interface Theme50DocumentData {
  /**
   * light field in *theme_50*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_50.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme50DocumentDataLightItem>>;
}
/**
 * Item in theme_50 → light
 *
 */
export interface Theme50DocumentDataLightItem {
  /**
   * name field in *theme_50 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_50.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-50">;
  /**
   * code field in *theme_50 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_50.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"fafafa">;
}
/**
 * theme_50 document from Prismic
 *
 * - **API ID**: `theme_50`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme50Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme50DocumentData>,
    "theme_50",
    Lang
  >;
/** Content for theme_500 documents */
interface Theme500DocumentData {
  /**
   * light field in *theme_500*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_500.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme500DocumentDataLightItem>>;
}
/**
 * Item in theme_500 → light
 *
 */
export interface Theme500DocumentDataLightItem {
  /**
   * name field in *theme_500 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_500.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-500">;
  /**
   * code field in *theme_500 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_500.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"737373">;
}
/**
 * theme_500 document from Prismic
 *
 * - **API ID**: `theme_500`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme500Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme500DocumentData>,
    "theme_500",
    Lang
  >;
/** Content for theme_600 documents */
interface Theme600DocumentData {
  /**
   * light field in *theme_600*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_600.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme600DocumentDataLightItem>>;
}
/**
 * Item in theme_600 → light
 *
 */
export interface Theme600DocumentDataLightItem {
  /**
   * name field in *theme_600 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_600.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-600">;
  /**
   * code field in *theme_600 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_600.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"525252">;
}
/**
 * theme_600 document from Prismic
 *
 * - **API ID**: `theme_600`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme600Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme600DocumentData>,
    "theme_600",
    Lang
  >;
/** Content for theme_700 documents */
interface Theme700DocumentData {
  /**
   * light field in *theme_700*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_700.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme700DocumentDataLightItem>>;
}
/**
 * Item in theme_700 → light
 *
 */
export interface Theme700DocumentDataLightItem {
  /**
   * name field in *theme_700 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_700.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-700">;
  /**
   * code field in *theme_700 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_700.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"404040">;
}
/**
 * theme_700 document from Prismic
 *
 * - **API ID**: `theme_700`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme700Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme700DocumentData>,
    "theme_700",
    Lang
  >;
/** Content for theme_800 documents */
interface Theme800DocumentData {
  /**
   * light field in *theme_800*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_800.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme800DocumentDataLightItem>>;
}
/**
 * Item in theme_800 → light
 *
 */
export interface Theme800DocumentDataLightItem {
  /**
   * name field in *theme_800 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_800.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-800">;
  /**
   * code field in *theme_800 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_800.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"262626">;
}
/**
 * theme_800 document from Prismic
 *
 * - **API ID**: `theme_800`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme800Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme800DocumentData>,
    "theme_800",
    Lang
  >;
/** Content for theme_900 documents */
interface Theme900DocumentData {
  /**
   * light field in *theme_900*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_900.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme900DocumentDataLightItem>>;
}
/**
 * Item in theme_900 → light
 *
 */
export interface Theme900DocumentDataLightItem {
  /**
   * name field in *theme_900 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_900.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-900">;
  /**
   * code field in *theme_900 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_900.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"171717">;
}
/**
 * theme_900 document from Prismic
 *
 * - **API ID**: `theme_900`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme900Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme900DocumentData>,
    "theme_900",
    Lang
  >;
/** Content for theme_950 documents */
interface Theme950DocumentData {
  /**
   * light field in *theme_950*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_950.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  light: prismic.GroupField<Simplify<Theme950DocumentDataLightItem>>;
}
/**
 * Item in theme_950 → light
 *
 */
export interface Theme950DocumentDataLightItem {
  /**
   * name field in *theme_950 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_950.light[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  name: prismic.SelectField<"neutral-950">;
  /**
   * code field in *theme_950 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_950.light[].code
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code: prismic.SelectField<"0a0a0a">;
}
/**
 * theme_950 document from Prismic
 *
 * - **API ID**: `theme_950`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme950Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme950DocumentData>,
    "theme_950",
    Lang
  >;
export type AllDocumentTypes =
  | ButtonDocument
  | ImageMaskDocument
  | LandingPageDocument
  | NavigationDocument
  | Theme100Document
  | Theme200Document
  | Theme300Document
  | Theme400Document
  | Theme50Document
  | Theme500Document
  | Theme600Document
  | Theme700Document
  | Theme800Document
  | Theme900Document
  | Theme950Document;
/**
 * Primary content in AarniSlice → Primary
 *
 */
interface AarniSliceSliceDefaultPrimary {
  /**
   * Title field in *AarniSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: aarni_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
}
/**
 * Default variation for AarniSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AarniSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AarniSliceSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *AarniSlice*
 *
 */
type AarniSliceSliceVariation = AarniSliceSliceDefault;
/**
 * AarniSlice Shared Slice
 *
 * - **API ID**: `aarni_slice`
 * - **Description**: `AarniSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AarniSliceSlice = prismic.SharedSlice<
  "aarni_slice",
  AarniSliceSliceVariation
>;
/**
 * Primary content in HeroSlice → Primary
 *
 */
interface HeroSliceSliceDefaultPrimary {
  /**
   * Title field in *HeroSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for Hero, uses <h1 /> tag.
   * - **API ID Path**: hero_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Subtitle field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Subtitle is under the Hero title.
   * - **API ID Path**: hero_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  subtitle: prismic.RichTextField;
  /**
   * Hero Image field in *HeroSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  hero_image: prismic.ImageField<never>;
  /**
   * Show Image Mask field in *HeroSlice → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_slice.primary.show_image_mask
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  show_image_mask: prismic.BooleanField;
  /**
   * Image Mask field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.image_mask
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  image_mask: prismic.ContentRelationshipField<"image_mask">;
  /**
   * Button field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.button
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button: prismic.ContentRelationshipField<"button">;
  /**
   * Button Label field in *HeroSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter label value for your button. Is visible for both button and links.
   * - **API ID Path**: hero_slice.primary.label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismic.KeyTextField;
  /**
   * Button Href field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.href
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  href: prismic.ContentRelationshipField<"landing_page">;
}
/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;
/**
 * Primary content in HeroSlice → Primary
 *
 */
interface HeroSliceSliceAvatarPrimary {
  /**
   * Title field in *HeroSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for Hero, uses <h1 /> tag.
   * - **API ID Path**: hero_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
}
/**
 * Avatar variation for HeroSlice Slice
 *
 * - **API ID**: `avatar`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceSliceAvatar = prismic.SharedSliceVariation<
  "avatar",
  Simplify<HeroSliceSliceAvatarPrimary>,
  never
>;
/**
 * Slice variation for *HeroSlice*
 *
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault | HeroSliceSliceAvatar;
/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: `HeroSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      ButtonDocumentData,
      ButtonDocument,
      ImageMaskDocumentData,
      ImageMaskDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      LandingPageDocument,
      NavigationDocumentData,
      NavigationDocumentDataNavigationLinksItem,
      NavigationDocument,
      Theme100DocumentData,
      Theme100DocumentDataLightItem,
      Theme100Document,
      Theme200DocumentData,
      Theme200DocumentDataLightItem,
      Theme200Document,
      Theme300DocumentData,
      Theme300DocumentDataLightItem,
      Theme300Document,
      Theme400DocumentData,
      Theme400DocumentDataLightItem,
      Theme400Document,
      Theme50DocumentData,
      Theme50DocumentDataLightItem,
      Theme50Document,
      Theme500DocumentData,
      Theme500DocumentDataLightItem,
      Theme500Document,
      Theme600DocumentData,
      Theme600DocumentDataLightItem,
      Theme600Document,
      Theme700DocumentData,
      Theme700DocumentDataLightItem,
      Theme700Document,
      Theme800DocumentData,
      Theme800DocumentDataLightItem,
      Theme800Document,
      Theme900DocumentData,
      Theme900DocumentDataLightItem,
      Theme900Document,
      Theme950DocumentData,
      Theme950DocumentDataLightItem,
      Theme950Document,
      AllDocumentTypes,
      AarniSliceSliceDefaultPrimary,
      AarniSliceSliceDefault,
      AarniSliceSliceVariation,
      AarniSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceDefault,
      HeroSliceSliceAvatarPrimary,
      HeroSliceSliceAvatar,
      HeroSliceSliceVariation,
      HeroSliceSlice,
    };
  }
}
