// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Button documents
 */
interface ButtonDocumentData {
  /**
   * Variant field in *Button*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: button.variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<"primary" | "secondary", "filled">;

  /**
   * Size field in *Button*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: xs
   * - **API ID Path**: button.size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  size: prismic.SelectField<"xs" | "sm" | "base" | "lg" | "xl", "filled">;

  /**
   * Full Width field in *Button*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: button.full_width
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  full_width: prismic.BooleanField;
}

/**
 * Button document from Prismic
 *
 * - **API ID**: `button`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ButtonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ButtonDocumentData>, "button", Lang>;

/**
 * Item in *Footer → Slogan Keys*
 */
export interface FooterDocumentDataSloganKeysItem {
  /**
   * word field in *Footer → Slogan Keys*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Use "key" words, which is part of the slogan on same row.
   * - **API ID Path**: footer.slogan_keys[].word
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  word: prismic.RichTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slogan field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Add your current slogan into footer. WIll be shown on right side, with same row as the "key" words.
   * - **API ID Path**: footer.slogan
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slogan: prismic.RichTextField;

  /**
   * Slogan Keys field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slogan_keys[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slogan_keys: prismic.GroupField<Simplify<FooterDocumentDataSloganKeysItem>>;

  /**
   * Social Icons field in *Footer*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_icons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_icons: prismic.ContentRelationshipField<"icons_list">;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for heroicon documents
 */
interface HeroiconDocumentData {
  /**
   * variant field in *heroicon*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose variant for the current icon. By default "solid" variant will be used for the icon.
   * - **Default Value**: solid
   * - **API ID Path**: heroicon.variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<"solid" | "outline" | "mini", "filled">;

  /**
   * name field in *heroicon*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: arrow-small-down
   * - **API ID Path**: heroicon.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<
    "arrow-small-down" | "arrow-small-up" | "arrow-small-right",
    "filled"
  >;
}

/**
 * heroicon document from Prismic
 *
 * - **API ID**: `heroicon`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeroiconDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HeroiconDocumentData>,
    "heroicon",
    Lang
  >;

/**
 * Item in *Icons List → Collection*
 */
export interface IconsListDocumentDataCollectionItem {
  /**
   * name field in *Icons List → Collection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icons_list.collection[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * icon field in *Icons List → Collection*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: tailwindcss
   * - **API ID Path**: icons_list.collection[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    | "tailwindcss"
    | "graphql"
    | "react"
    | "nextjs"
    | "GitHub"
    | "LinkedIn"
    | "Twitter",
    "filled"
  >;

  /**
   * href field in *Icons List → Collection*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional value for current icon. Can be used for example with social icons, where you want to redirect user into LinkedIn etc.
   * - **API ID Path**: icons_list.collection[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField;
}

/**
 * Content for Icons List documents
 */
interface IconsListDocumentData {
  /**
   * Show Icons field in *Icons List*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: icons_list.show_icons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_icons: prismic.BooleanField;

  /**
   * Collection field in *Icons List*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icons_list.collection[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  collection: prismic.GroupField<Simplify<IconsListDocumentDataCollectionItem>>;
}

/**
 * Icons List document from Prismic
 *
 * - **API ID**: `icons_list`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IconsListDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IconsListDocumentData>,
    "icons_list",
    Lang
  >;

/**
 * Item in *Image Gallery → Gallery*
 */
export interface ImageGalleryDocumentDataGalleryItem {
  /**
   * image field in *Image Gallery → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Image Gallery documents
 */
interface ImageGalleryDocumentData {
  /**
   * Gallery field in *Image Gallery*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<ImageGalleryDocumentDataGalleryItem>>;
}

/**
 * Image Gallery document from Prismic
 *
 * - **API ID**: `image_gallery`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImageGalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ImageGalleryDocumentData>,
    "image_gallery",
    Lang
  >;

/**
 * Content for Image Mask documents
 */
interface ImageMaskDocumentData {
  /**
   * variant field in *Image Mask*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose mask variant (default is "avatar")
   * - **Default Value**: avatar
   * - **API ID Path**: image_mask.variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<"avatar" | "fullWidth", "filled">;
}

/**
 * Image Mask document from Prismic
 *
 * - **API ID**: `image_mask`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImageMaskDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ImageMaskDocumentData>,
    "image_mask",
    Lang
  >;

type LandingPageDocumentDataSlicesSlice = HeroSliceSlice | CardSliceSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Item in *navigation → Navigation Links*
 */
export interface NavigationDocumentDataNavigationLinksItem {
  /**
   * Link Name field in *navigation → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_links[].link_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_name: prismic.KeyTextField;

  /**
   * Link Href field in *navigation → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_links[].link_href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_href: prismic.LinkField;
}

/**
 * Content for navigation documents
 */
interface NavigationDocumentData {
  /**
   * color field in *navigation*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  color: prismic.ContentRelationshipField<
    | "theme_50"
    | "theme_100"
    | "theme_200"
    | "theme_300"
    | "theme_400"
    | "theme_500"
    | "theme_600"
    | "theme_700"
    | "theme_800"
    | "theme_900"
    | "theme_950"
  >;

  /**
   * position field in *navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: navigation.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  position: prismic.BooleanField;

  /**
   * Navigation Title field in *navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  navigation_title: prismic.KeyTextField;

  /**
   * Navigation Links field in *navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_links: prismic.GroupField<
    Simplify<NavigationDocumentDataNavigationLinksItem>
  >;
}

/**
 * navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type ProjectPostDocumentDataSlicesSlice =
  | ContentBlockSliceSlice
  | HeroSliceSlice;

/**
 * Content for Project Post documents
 */
interface ProjectPostDocumentData {
  /**
   * Slice Zone field in *Project Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectPostDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Project Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Project Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Project Post document from Prismic
 *
 * - **API ID**: `project_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectPostDocumentData>,
    "project_post",
    Lang
  >;

/**
 * Item in *theme_100 → light*
 */
export interface Theme100DocumentDataLightItem {
  /**
   * name field in *theme_100 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_100.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-100">;

  /**
   * code field in *theme_100 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_100.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"f5f5f5">;
}

/**
 * Content for theme_100 documents
 */
interface Theme100DocumentData {
  /**
   * light field in *theme_100*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_100.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme100DocumentDataLightItem>>;
}

/**
 * theme_100 document from Prismic
 *
 * - **API ID**: `theme_100`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme100Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme100DocumentData>,
    "theme_100",
    Lang
  >;

/**
 * Item in *theme_200 → light*
 */
export interface Theme200DocumentDataLightItem {
  /**
   * name field in *theme_200 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_200.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-200">;

  /**
   * code field in *theme_200 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_200.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"e5e5e5">;
}

/**
 * Content for theme_200 documents
 */
interface Theme200DocumentData {
  /**
   * light field in *theme_200*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_200.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme200DocumentDataLightItem>>;
}

/**
 * theme_200 document from Prismic
 *
 * - **API ID**: `theme_200`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme200Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme200DocumentData>,
    "theme_200",
    Lang
  >;

/**
 * Item in *theme_300 → light*
 */
export interface Theme300DocumentDataLightItem {
  /**
   * name field in *theme_300 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_300.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-300">;

  /**
   * code field in *theme_300 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_300.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"d4d4d4">;
}

/**
 * Content for theme_300 documents
 */
interface Theme300DocumentData {
  /**
   * light field in *theme_300*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_300.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme300DocumentDataLightItem>>;
}

/**
 * theme_300 document from Prismic
 *
 * - **API ID**: `theme_300`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme300Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme300DocumentData>,
    "theme_300",
    Lang
  >;

/**
 * Item in *theme_400 → light*
 */
export interface Theme400DocumentDataLightItem {
  /**
   * name field in *theme_400 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_400.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-400">;

  /**
   * code field in *theme_400 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_400.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"a3a3a3">;
}

/**
 * Content for theme_400 documents
 */
interface Theme400DocumentData {
  /**
   * light field in *theme_400*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_400.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme400DocumentDataLightItem>>;
}

/**
 * theme_400 document from Prismic
 *
 * - **API ID**: `theme_400`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme400Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme400DocumentData>,
    "theme_400",
    Lang
  >;

/**
 * Item in *theme_50 → light*
 */
export interface Theme50DocumentDataLightItem {
  /**
   * name field in *theme_50 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_50.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-50">;

  /**
   * code field in *theme_50 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_50.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"fafafa">;
}

/**
 * Content for theme_50 documents
 */
interface Theme50DocumentData {
  /**
   * light field in *theme_50*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_50.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme50DocumentDataLightItem>>;
}

/**
 * theme_50 document from Prismic
 *
 * - **API ID**: `theme_50`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme50Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme50DocumentData>,
    "theme_50",
    Lang
  >;

/**
 * Item in *theme_500 → light*
 */
export interface Theme500DocumentDataLightItem {
  /**
   * name field in *theme_500 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_500.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-500">;

  /**
   * code field in *theme_500 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_500.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"737373">;
}

/**
 * Content for theme_500 documents
 */
interface Theme500DocumentData {
  /**
   * light field in *theme_500*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_500.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme500DocumentDataLightItem>>;
}

/**
 * theme_500 document from Prismic
 *
 * - **API ID**: `theme_500`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme500Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme500DocumentData>,
    "theme_500",
    Lang
  >;

/**
 * Item in *theme_600 → light*
 */
export interface Theme600DocumentDataLightItem {
  /**
   * name field in *theme_600 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_600.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-600">;

  /**
   * code field in *theme_600 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_600.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"525252">;
}

/**
 * Content for theme_600 documents
 */
interface Theme600DocumentData {
  /**
   * light field in *theme_600*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_600.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme600DocumentDataLightItem>>;
}

/**
 * theme_600 document from Prismic
 *
 * - **API ID**: `theme_600`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme600Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme600DocumentData>,
    "theme_600",
    Lang
  >;

/**
 * Item in *theme_700 → light*
 */
export interface Theme700DocumentDataLightItem {
  /**
   * name field in *theme_700 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_700.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-700">;

  /**
   * code field in *theme_700 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_700.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"404040">;
}

/**
 * Content for theme_700 documents
 */
interface Theme700DocumentData {
  /**
   * light field in *theme_700*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_700.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme700DocumentDataLightItem>>;
}

/**
 * theme_700 document from Prismic
 *
 * - **API ID**: `theme_700`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme700Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme700DocumentData>,
    "theme_700",
    Lang
  >;

/**
 * Item in *theme_800 → light*
 */
export interface Theme800DocumentDataLightItem {
  /**
   * name field in *theme_800 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_800.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-800">;

  /**
   * code field in *theme_800 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_800.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"262626">;
}

/**
 * Content for theme_800 documents
 */
interface Theme800DocumentData {
  /**
   * light field in *theme_800*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_800.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme800DocumentDataLightItem>>;
}

/**
 * theme_800 document from Prismic
 *
 * - **API ID**: `theme_800`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme800Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme800DocumentData>,
    "theme_800",
    Lang
  >;

/**
 * Item in *theme_900 → light*
 */
export interface Theme900DocumentDataLightItem {
  /**
   * name field in *theme_900 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_900.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-900">;

  /**
   * code field in *theme_900 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_900.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"171717">;
}

/**
 * Content for theme_900 documents
 */
interface Theme900DocumentData {
  /**
   * light field in *theme_900*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_900.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme900DocumentDataLightItem>>;
}

/**
 * theme_900 document from Prismic
 *
 * - **API ID**: `theme_900`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme900Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme900DocumentData>,
    "theme_900",
    Lang
  >;

/**
 * Item in *theme_950 → light*
 */
export interface Theme950DocumentDataLightItem {
  /**
   * name field in *theme_950 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_950.light[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<"neutral-950">;

  /**
   * code field in *theme_950 → light*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_950.light[].code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  code: prismic.SelectField<"0a0a0a">;
}

/**
 * Content for theme_950 documents
 */
interface Theme950DocumentData {
  /**
   * light field in *theme_950*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_950.light[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  light: prismic.GroupField<Simplify<Theme950DocumentDataLightItem>>;
}

/**
 * theme_950 document from Prismic
 *
 * - **API ID**: `theme_950`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Theme950Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Theme950DocumentData>,
    "theme_950",
    Lang
  >;

export type AllDocumentTypes =
  | ButtonDocument
  | FooterDocument
  | HeroiconDocument
  | IconsListDocument
  | ImageGalleryDocument
  | ImageMaskDocument
  | LandingPageDocument
  | NavigationDocument
  | ProjectPostDocument
  | Theme100Document
  | Theme200Document
  | Theme300Document
  | Theme400Document
  | Theme50Document
  | Theme500Document
  | Theme600Document
  | Theme700Document
  | Theme800Document
  | Theme900Document
  | Theme950Document;

/**
 * Primary content in *CardSlice → Primary*
 */
export interface CardSliceSliceDefaultPrimary {
  /**
   * title field in *CardSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * subtitle field in *CardSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Primary content in *CardSlice → Items*
 */
export interface CardSliceSliceDefaultItem {
  /**
   * Card Image field in *CardSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Name field in *CardSlice → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter name for current card item.
   * - **API ID Path**: card_slice.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Collection field in *CardSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].collection
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  collection: prismic.ContentRelationshipField<"icons_list">;

  /**
   * Description field in *CardSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description for current card item.
   * - **API ID Path**: card_slice.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Icon field in *CardSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  icon: prismic.ContentRelationshipField<"heroicon">;

  /**
   * Button field in *CardSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.ContentRelationshipField<"button">;

  /**
   * Button Label field in *CardSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Button Href field in *CardSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.ContentRelationshipField;
}

/**
 * Default variation for CardSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardSliceSliceDefaultPrimary>,
  Simplify<CardSliceSliceDefaultItem>
>;

/**
 * Slice variation for *CardSlice*
 */
type CardSliceSliceVariation = CardSliceSliceDefault;

/**
 * CardSlice Shared Slice
 *
 * - **API ID**: `card_slice`
 * - **Description**: CardSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceSlice = prismic.SharedSlice<
  "card_slice",
  CardSliceSliceVariation
>;

/**
 * Primary content in *ContentBlockSlice → Primary*
 */
export interface ContentBlockSliceSliceDefaultPrimary {
  /**
   * title field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * subtitle field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Hashtag field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.hashtag
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hashtag: prismic.ContentRelationshipField<"icons_list">;

  /**
   * Stack field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.stack
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  stack: prismic.ContentRelationshipField<"icons_list">;

  /**
   * Content field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Images field in *ContentBlockSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block_slice.primary.images
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  images: prismic.ContentRelationshipField<"image_gallery">;
}

/**
 * Default variation for ContentBlockSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentBlockSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentBlockSlice*
 */
type ContentBlockSliceSliceVariation = ContentBlockSliceSliceDefault;

/**
 * ContentBlockSlice Shared Slice
 *
 * - **API ID**: `content_block_slice`
 * - **Description**: ContentBlockSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSliceSlice = prismic.SharedSlice<
  "content_block_slice",
  ContentBlockSliceSliceVariation
>;

/**
 * Primary content in *HeroSlice → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Title field in *HeroSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for Hero, uses <h1 /> tag.
   * - **API ID Path**: hero_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Subtitle is under the Hero title.
   * - **API ID Path**: hero_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Hero Image field in *HeroSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Image Mask field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.image_mask
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_mask: prismic.ContentRelationshipField<"image_mask">;

  /**
   * icon field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  icon: prismic.ContentRelationshipField<"heroicon">;

  /**
   * Button field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.ContentRelationshipField<"button">;

  /**
   * Button Label field in *HeroSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter label value for your button. Is visible for both button and links.
   * - **API ID Path**: hero_slice.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Button Href field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.ContentRelationshipField<"landing_page">;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSlice → Primary*
 */
export interface HeroSliceSliceFullWidthPrimary {
  /**
   * Title field in *HeroSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for Hero, uses <h1 /> tag.
   * - **API ID Path**: hero_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Subtitle is under the Hero title.
   * - **API ID Path**: hero_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Hero Image field in *HeroSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Image Mask field in *HeroSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.image_mask
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_mask: prismic.ContentRelationshipField<"image_mask">;
}

/**
 * Full Width variation for HeroSlice Slice
 *
 * - **API ID**: `fullWidth`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceFullWidth = prismic.SharedSliceVariation<
  "fullWidth",
  Simplify<HeroSliceSliceFullWidthPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault | HeroSliceSliceFullWidth;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ButtonDocument,
      ButtonDocumentData,
      FooterDocument,
      FooterDocumentData,
      HeroiconDocument,
      HeroiconDocumentData,
      IconsListDocument,
      IconsListDocumentData,
      ImageGalleryDocument,
      ImageGalleryDocumentData,
      ImageMaskDocument,
      ImageMaskDocumentData,
      LandingPageDocument,
      LandingPageDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      ProjectPostDocument,
      ProjectPostDocumentData,
      Theme100Document,
      Theme100DocumentData,
      Theme200Document,
      Theme200DocumentData,
      Theme300Document,
      Theme300DocumentData,
      Theme400Document,
      Theme400DocumentData,
      Theme50Document,
      Theme50DocumentData,
      Theme500Document,
      Theme500DocumentData,
      Theme600Document,
      Theme600DocumentData,
      Theme700Document,
      Theme700DocumentData,
      Theme800Document,
      Theme800DocumentData,
      Theme900Document,
      Theme900DocumentData,
      Theme950Document,
      Theme950DocumentData,
      AllDocumentTypes,
      CardSliceSlice,
      CardSliceSliceVariation,
      CardSliceSliceDefault,
      ContentBlockSliceSlice,
      ContentBlockSliceSliceVariation,
      ContentBlockSliceSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      HeroSliceSliceFullWidth,
    };
  }
}
