// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  aarni_slice: dynamic(() => import("./AarniSlice")),
  // hero_slice: dynamic(() => import("./HeroSlice")),
  hero_slice: dynamic(() => import("./HeroSlice"), { ssr: false })
};