// Code generated by Slice Machine. DO NOT EDIT.
import dynamic from 'next/dynamic';

export const components = {
  hero_slice: dynamic(() => import('./HeroSlice')),
  aarni_slice: dynamic(() => import('./AarniSlice')),
  // Add more slices here as needed
};
