version: '3'

services:
  next-app:
    container_name: portfolio-production
    build:
      context: ../../
      dockerfile: ./docker/production/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - personal-portfolio

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  personal-portfolio:
    external: true